package com.example.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.example.dynamodb.converter.LocalDateConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

import javax.validation.constraints.NotNull;
import java.time.LocalDate;

@DynamoDBTable(tableName="customer")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Component
public class Customer {

  @DynamoDBHashKey(attributeName = "customerId")
  @DynamoDBAutoGeneratedKey
  String customerId;
  @NotNull
  String name;
  @NotNull
  String role;

  @DynamoDBTypeConverted( converter = LocalDateConverter.class )
  LocalDate dateOfBirth;
}
